# Generated by Django 4.2.1 on 2023-12-29 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0010_remove_women_women_women_time_cr_9f33c2_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='women',
            options={'ordering': ['id']},
        ),
    ]
