# Generated by Django 4.2.1 on 2023-12-29 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0011_alter_women_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='husband',
            name='m_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
